PRAGMA foreign_keys = ON;

CREATE TABLE users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT UNIQUE NOT NULL,
    PASSWORD_HASH TEXT NOT NULL
);

CREATE TABLE maps (
    MAP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    OWNER_ID INTEGER NOT NULL,
    FOREIGN KEY (OWNER_ID) REFERENCES users(ID) ON DELETE CASCADE
);

CREATE TABLE mapshares (
    SHARE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MAP_ID INTEGER NOT NULL,
    EDITOR_ID INTEGER NOT NULL,
    FOREIGN KEY (MAP_ID) REFERENCES maps(MAP_ID) ON DELETE CASCADE,
    FOREIGN KEY (EDITOR_ID) REFERENCES users(ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX mapshares_unique
          ON mapshares(map_id, user_id);
